-- MySQL Script generated by MySQL Workbench
-- Sun Oct  3 18:12:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alkemy_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alkemy_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alkemy_v2` DEFAULT CHARACTER SET utf8 ;
USE `alkemy_v2` ;

-- -----------------------------------------------------
-- Table `alkemy_v2`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemy_v2`.`categories` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `categ_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `categ_nombre_UNIQUE` (`categ_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alkemy_v2`.`transaction_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemy_v2`.`transaction_types` (
  `id_types` INT NOT NULL AUTO_INCREMENT,
  `name_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_types`),
  UNIQUE INDEX `name_UNIQUE` (`name_type` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alkemy_v2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemy_v2`.`users` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `is_admin` TINYINT(1) NULL,
  PRIMARY KEY (`email`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alkemy_v2`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemy_v2`.`transactions` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `creation_date` DATE NOT NULL DEFAULT current_timestamp(),
  `concept` VARCHAR(45) NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `modification_date` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
  `fk_type` INT NOT NULL,
  `fk_category` INT NOT NULL,
  `owner` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_categoria_idx` (`fk_category` ASC) ,
  INDEX `fk_type_idx` (`fk_type` ASC) ,
  INDEX `owner_idx` (`owner` ASC) ,
  CONSTRAINT `fk_category`
    FOREIGN KEY (`fk_category`)
    REFERENCES `alkemy_v2`.`categories` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_type`
    FOREIGN KEY (`fk_type`)
    REFERENCES `alkemy_v2`.`transaction_types` (`id_types`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `owner`
    FOREIGN KEY (`owner`)
    REFERENCES `alkemy_v2`.`users` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `alkemy_v2` ;

-- -----------------------------------------------------
-- Placeholder table for view `alkemy_v2`.`view_transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alkemy_v2`.`view_transactions` (`'Owner'` INT, `'Date'` INT, `Concept` INT, `Amount` INT, `Category` INT, `'Type'` INT);

-- -----------------------------------------------------
-- View `alkemy_v2`.`view_transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `alkemy_v2`.`view_transactions`;
USE `alkemy_v2`;
CREATE  OR REPLACE VIEW `view_transactions` AS
SELECT a.id_transaction AS ID, a.owner as 'Owner',a.creation_date as 'Date', a.concept as Concept, a.amount as Amount, b.id_category, b.categ_name as Category, c.name_type as 'Type' FROM transactions a
LEFT JOIN categories b
ON a.fk_category = b.id_category
LEFT JOIN transaction_types c
ON a.fk_type = c.id_types
ORDER BY a.creation_date DESC;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `transaction_types` (`id_types`, `name_type`) VALUES
(2, 'Expense'),
(1, 'Income');

INSERT INTO `categories` (`id_category`, `categ_name`) VALUES
(2, 'Automobile'),
(1, 'Food'),
(4, 'Pets'),
(3, 'Pharmacy'),
(5, 'Salary'),
(6, 'Vacations');