//{Income, Expense, Last10, Balance, Categories}
// {ID: 92,
// Date: "2021-09-28",
// Concept: "upd2",
// Amount: 40,
// id_category: 2,
// Category: "Automobile",
// Type: "Income",}
export const Income = {
    success: true,
    data: [
        {
            ID: 91,
            Date: "2021-09-28",
            Concept: "upd3",
            Amount: 30,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 92,
            Date: "2021-09-28",
            Concept: "upd2",
            Amount: 40,
            id_category: 2,
            Category: "Automobile",
            Type: "Income",
        },
        {
            ID: 104,
            Date: "2021-09-24",
            Concept: "Coco___Miedosa",
            Amount: 400,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 95,
            Date: "2021-09-24",
            Concept: "CocoMiedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 96,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 97,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa ",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 98,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa #$%",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 99,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 103,
            Date: "2021-09-24",
            Concept: "Coco___Miedosa",
            Amount: 400,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 102,
            Date: "2021-09-24",
            Concept: "Coco___Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 101,
            Date: "2021-09-24",
            Concept: "Coco___Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 100,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 94,
            Date: "2021-09-23",
            Concept: "CocoVendetta",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 93,
            Date: "2021-09-23",
            Concept: "CocoVendetta",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 78,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 77,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 76,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 75,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 74,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 73,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 72,
            Date: "2021-09-23",
            Concept: "sequelize test",
            Amount: 666,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 41,
            Date: "2021-09-06",
            Concept: "Income13",
            Amount: 333,
            id_category: 6,
            Category: "Vacations",
            Type: "Income",
        },
        {
            ID: 40,
            Date: "2021-08-05",
            Concept: "Income12",
            Amount: 444,
            id_category: 5,
            Category: "Salary",
            Type: "Income",
        },
        {
            ID: 39,
            Date: "2021-07-17",
            Concept: "Income11",
            Amount: 555,
            id_category: 4,
            Category: "Pets",
            Type: "Income",
        },
        {
            ID: 38,
            Date: "2021-07-16",
            Concept: "Income10",
            Amount: 999,
            id_category: 2,
            Category: "Automobile",
            Type: "Income",
        },
        {
            ID: 37,
            Date: "2021-07-15",
            Concept: "Income9",
            Amount: 888,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 34,
            Date: "2021-07-06",
            Concept: "Income7",
            Amount: 333,
            id_category: 6,
            Category: "Vacations",
            Type: "Income",
        },
        {
            ID: 33,
            Date: "2021-07-05",
            Concept: "Income6",
            Amount: 444,
            id_category: 5,
            Category: "Salary",
            Type: "Income",
        },
        {
            ID: 32,
            Date: "2021-07-04",
            Concept: "Income5",
            Amount: 555,
            id_category: 4,
            Category: "Pets",
            Type: "Income",
        },
        {
            ID: 35,
            Date: "2021-07-03",
            Concept: "Income4",
            Amount: 666,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 31,
            Date: "2021-07-02",
            Concept: "Income3",
            Amount: 999,
            id_category: 2,
            Category: "Automobile",
            Type: "Income",
        },
        {
            ID: 30,
            Date: "2021-07-01",
            Concept: "Income2",
            Amount: 888,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 36,
            Date: "2021-06-28",
            Concept: "Income8",
            Amount: 777,
            id_category: 4,
            Category: "Pets",
            Type: "Income",
        },
        {
            ID: 29,
            Date: "2021-06-28",
            Concept: "Income1",
            Amount: 777,
            id_category: 4,
            Category: "Pets",
            Type: "Income",
        },
        {
            ID: 42,
            Date: "2021-05-03",
            Concept: "Income14",
            Amount: 666,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
    ],
};

export const Expense = {
    success: true,
    data: [
        {
            ID: 69,
            Date: "2021-09-16",
            Concept: "Car",
            Amount: 2,
            id_category: 4,
            Category: "Pets",
            Type: "Expense",
        },
        {
            ID: 68,
            Date: "2021-09-16",
            Concept: "Car",
            Amount: 2,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Expense",
        },
        {
            ID: 67,
            Date: "2021-09-16",
            Concept: "cvx",
            Amount: 2,
            id_category: 2,
            Category: "Automobile",
            Type: "Expense",
        },
        {
            ID: 66,
            Date: "2021-09-16",
            Concept: "asd",
            Amount: 2,
            id_category: 4,
            Category: "Pets",
            Type: "Expense",
        },
        {
            ID: 65,
            Date: "2021-09-16",
            Concept: "Car",
            Amount: 3,
            id_category: 6,
            Category: "Vacations",
            Type: "Expense",
        },
        {
            ID: 55,
            Date: "2021-09-06",
            Concept: "Expense13",
            Amount: 333,
            id_category: 6,
            Category: "Vacations",
            Type: "Expense",
        },
        {
            ID: 54,
            Date: "2021-08-05",
            Concept: "Expense12",
            Amount: 214,
            id_category: 5,
            Category: "Salary",
            Type: "Expense",
        },
        {
            ID: 53,
            Date: "2021-07-17",
            Concept: "Expense11",
            Amount: 555,
            id_category: 4,
            Category: "Pets",
            Type: "Expense",
        },
        {
            ID: 52,
            Date: "2021-07-16",
            Concept: "Expense10",
            Amount: 119,
            id_category: 2,
            Category: "Automobile",
            Type: "Expense",
        },
        {
            ID: 51,
            Date: "2021-07-15",
            Concept: "Expense9",
            Amount: 888,
            id_category: 1,
            Category: "Food",
            Type: "Expense",
        },
        {
            ID: 48,
            Date: "2021-07-06",
            Concept: "Expense7",
            Amount: 333,
            id_category: 6,
            Category: "Vacations",
            Type: "Expense",
        },
        {
            ID: 47,
            Date: "2021-07-05",
            Concept: "Expense6",
            Amount: 214,
            id_category: 5,
            Category: "Salary",
            Type: "Expense",
        },
        {
            ID: 46,
            Date: "2021-07-04",
            Concept: "Expense5",
            Amount: 555,
            id_category: 4,
            Category: "Pets",
            Type: "Expense",
        },
        {
            ID: 49,
            Date: "2021-07-03",
            Concept: "Expense4",
            Amount: 666,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Expense",
        },
        {
            ID: 45,
            Date: "2021-07-02",
            Concept: "Expense3",
            Amount: 119,
            id_category: 2,
            Category: "Automobile",
            Type: "Expense",
        },
        {
            ID: 44,
            Date: "2021-07-01",
            Concept: "Expense2",
            Amount: 888,
            id_category: 1,
            Category: "Food",
            Type: "Expense",
        },
        {
            ID: 50,
            Date: "2021-06-28",
            Concept: "Expense8",
            Amount: 337,
            id_category: 4,
            Category: "Pets",
            Type: "Expense",
        },
        {
            ID: 43,
            Date: "2021-06-28",
            Concept: "Expense1",
            Amount: 337,
            id_category: 4,
            Category: "Pets",
            Type: "Expense",
        },
        {
            ID: 56,
            Date: "2021-05-03",
            Concept: "Expense14",
            Amount: 666,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Expense",
        },
    ],
};

export const Last10 = {
    success: true,
    data: [
        {
            ID: 92,
            Date: "2021-09-28",
            Concept: "upd2",
            Amount: 40,
            id_category: 2,
            Category: "Automobile",
            Type: "Income",
        },
        {
            ID: 91,
            Date: "2021-09-28",
            Concept: "upd3",
            Amount: 30,
            id_category: 1,
            Category: "Food",
            Type: "Income",
        },
        {
            ID: 100,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 95,
            Date: "2021-09-24",
            Concept: "CocoMiedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 102,
            Date: "2021-09-24",
            Concept: "Coco___Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 99,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 96,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 98,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa #$%",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 101,
            Date: "2021-09-24",
            Concept: "Coco___Miedosa",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
        {
            ID: 97,
            Date: "2021-09-24",
            Concept: "Coco_Miedosa ",
            Amount: 300,
            id_category: 3,
            Category: "Pharmacy",
            Type: "Income",
        },
    ],
};

export const Balance = {
    success: true,
    data: {
        balance: 11621,
    },
};

export const Categories = {
    success: true,
    data: [
        {
            id_category: 2,
            categ_name: "Automobile",
        },
        {
            id_category: 1,
            categ_name: "Food",
        },
        {
            id_category: 4,
            categ_name: "Pets",
        },
        {
            id_category: 3,
            categ_name: "Pharmacy",
        },
        {
            id_category: 5,
            categ_name: "Salary",
        },
        {
            id_category: 6,
            categ_name: "Vacations",
        },
    ],
};
